image: mcr.microsoft.com/dotnet/sdk:6.0

clone:
  lfs: true

definitions:
  services:
    postgres:
      image: postgres
      environment:
        POSTGRES_DB: localDatabase
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: localPassword

pipelines:
  default:
    - parallel:
        - step:
            name: Test
            script:
              - REPORTS_PATH=./test-reports/build_${BITBUCKET_BUILD_NUMBER}
              - cd Backend && dotnet test
            services:
              - postgres
